services:
  postgre-db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: relive-postgre
    volumes:
      - ./postgres:/var/lib/postgresql/data

  mongo-db:
    image: mongo:5.0.3
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    container_name: relive-mongo
    volumes:
      - ./mongo:/data/db

volumes:
  postgres:
  mongo: